/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Jessica
 */
public class Cuaderno extends Interna {

    /**
     * Creates new form Cargar
     */
    
    
    public Cuaderno(JFrame previo) {
        
        super(previo,true);
        
        initComponents();
        
        this.setName("cuaderno");
        
        this.getContentPane().setBackground(ColorPrincipal);
        this.setBounds(dimForms);

        this.setTitle("SistemaComunal - Cuaderno Electoral");
               
        llenar();
        
    }
    
    public String getStr(String str, int tam)
    {
        String ret=str;
        int dif=tam-str.length();
        for (int i = 0; i < dif; i++) 
        {
            ret+=" ";
        }
        return ret;
    }
    
    public void llenar()
    {
        
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14));
        jTextArea1.setText("\n        "+getStr("Apellidos y Nombres: ",100)+"Cédula:");
        String text=jTextArea1.getText();
        jTextArea1.setText(text+"\n______________________________________________________________________________________");
        Calendar c = Calendar.getInstance();
       
        int dia = c.get(Calendar.DATE);
        int mes = c.get(Calendar.MONTH);
        int annio = c.get(Calendar.YEAR)-16;
        
        String fecha=annio+"-"+(mes+1)+"-"+dia;
        
        
        String data[][] = (String[][])op.select_orderby("Persona","nombres, apellidos, cedula","fecha_nac<=DATE('"+fecha+"')","apellidos, nombres",con);
        
        for (int i = 0; i < data.length; i++)
        {
            String num="";
            text=jTextArea1.getText();
            if(i<9)
            {
                num=" ";
            }
            num+=((i+1)+":");
           
            jTextArea1.setText(text+"\n"+num+"     "+getStr(data[i][1]+" "+data[i][0],100)+"C.I: "+data[i][2]);
            text=jTextArea1.getText();
            jTextArea1.setText(text+"\n______________________________________________________________________________________");    

        }
        
        if(data.length==0)
        {
            jTextArea1.setText("");
            jPanel1.setVisible(false);
            JOptionPane.showMessageDialog(null, "No se encontraron registros");
        }
        
        jTextArea1.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
