/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Habitante;
import java.io.*;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.swing.JOptionPane;
import org.jdom.*;
import org.jdom.input.SAXBuilder;
import org.jdom.output.XMLOutputter;
/**
 *
 * @author Jessica
 */
public class DatosViuda extends Datos{

    /**
     * 
     */
    
    public DatosViuda(Interna in) 
    {
        super(in);
        initComponents();
        
        jLabel6.setFont(Etiqueta);
        jLabel6.setForeground(NegroEtiqueta);
        jLabel8.setFont(Etiqueta);
        jLabel8.setForeground(NegroEtiqueta);
        jLabel9.setFont(Etiqueta);
        jLabel9.setForeground(NegroEtiqueta);
        jLabel10.setFont(Etiqueta);
        jLabel10.setForeground(NegroEtiqueta);
        jLabel11.setFont(Etiqueta);
        jLabel11.setForeground(NegroEtiqueta);
        jLabel12.setFont(Etiqueta);
        jLabel12.setForeground(NegroEtiqueta);
        
        jLabel7.setFont(Titulo);
        jLabel7.setForeground(NegroEtiqueta);
            
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        crear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nom1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ced1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nac1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        nac2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nom2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ced2 = new javax.swing.JTextField();

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        crear.setText("Crear Documento");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        crear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel7.setText("Datos Requeridos");

        nom1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel6.setText("Nombre testigo 1:");

        ced1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel8.setText("Nacionalidad testigo 1:");

        nac1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel9.setText("Cédula testigo 1:");

        nac2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel10.setText("Cédula testigo 2:");

        nom2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        jLabel11.setText("Nombre testigo 2:");

        jLabel12.setText("Nacionalidad testigo 2:");

        ced2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ElemKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 842, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ced1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(22, 22, 22)
                                    .addComponent(nac1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ced2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addGap(22, 22, 22)
                                    .addComponent(nac2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(53, 53, 53)
                                .addComponent(nom2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(crear)
                .addGap(350, 350, 350))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(nom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(ced2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ced1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(38, 38, 38)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crear)
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void crear_docx(String[] param,ZipOutputStream zos, File f) throws FileNotFoundException, IOException, JDOMException
    {
        if(f.isDirectory())
        {
            String[] data=f.list();
            for (String data1 : data)
            {
                crear_docx(param,zos, new File(f.getPath()+"/" + data1));
            }
        }
        else
        {
 
            ZipEntry entry = new ZipEntry(f.getPath().substring(13));
            zos.putNextEntry(entry);
   
            if(f.getPath().compareTo("cartas\\viuda\\word\\document.xml")==0)
            {
                SAXBuilder builder = new SAXBuilder();  
                Document documentJDOM = builder.build(new FileInputStream(f));   
                List<Element> lista, Lpag, p1, p2;
                lista = documentJDOM.getRootElement().getChildren();
                Lpag = lista.get(0).getChildren();
                p1 = Lpag.get(2).getChildren();
                p2 = Lpag.get(3).getChildren();
                int pos=0;
 
                for(Element e: p1)
                {
                    if(e.getName().compareTo("r")==0)
                    {
                        List<Attribute> Lattr = e.getAttributes();
                        if(Lattr.size()>0)
                        {
                            if(Lattr.get(0).getValue().compareTo("00DB684A")==0)
                            {
                                List<Element> listR = e.getChildren();
                                listR.get(1).setText(param[pos]);
                                pos++;
                            }
                        }
                    }
                }
        
                for(Element e: p2)
                {
                    if(e.getName().compareTo("r")==0)
                    {
                        List<Attribute> Lattr = e.getAttributes();
                        if(Lattr.size()>0)
                        {
                            if(Lattr.get(0).getValue().compareTo("00DB684A")==0)
                            {
                                List<Element> listR = e.getChildren();
                                listR.get(1).setText(param[pos]);
                                pos++;
                            }
                        }
                    }
                }
        
                XMLOutputter salida = new XMLOutputter();
                salida.output(documentJDOM,new FileOutputStream("cartas\\viuda\\word\\document.xml"));
            }
            
            BufferedReader buffer = new BufferedReader(new FileReader(f));
          
            String linea=buffer.readLine();
            while(linea!=null)
            {
                zos.write(linea.getBytes());
                linea=buffer.readLine();
            }
            zos.closeEntry(); 
        }
    }
    
    
    public void evento()
    {
        String nombre1 = nom1.getText();
        String cedula1 = ced1.getText();
        String nacionalidad1 = nac1.getText();
        String nombre2 = nom2.getText();
        String cedula2 = ced2.getText();
        String nacionalidad2 = nac2.getText();
        
        if(nombre1.compareTo("")!=0 && cedula1.compareTo("")!=0 && nacionalidad1.compareTo("")!=0 && nombre2.compareTo("")!=0 && cedula2.compareTo("")!=0 && nacionalidad2.compareTo("")!=0)
        {
            
            Calendar c = Calendar.getInstance();
            
            int dia = c.get(Calendar.DATE);
            int mes = c.get(Calendar.MONTH);
            int annio = c.get(Calendar.YEAR);
            
            String param[] = new String[9];
            param[0]=nom1.getText()+", "+nom2.getText();
            param[1]=nac1.getText()+", "+nac2.getText()+" ";
            param[2]=ced1.getText()+", "+ced2.getText();
            param[3]=h.apellido+" "+h.nombre;
            param[4]=h.cedula;
            param[5]="VIUDA.";
            param[6]=String.valueOf(dia);
            param[7]=getMes(mes);
            param[8]=String.valueOf(annio);
            
            try
            {
                
            FileOutputStream fos = new FileOutputStream("cartas\\generada.docx");
            ZipOutputStream zos = new ZipOutputStream(fos);
        
            File f = new File("cartas\\viuda");
        
            crear_docx(param,zos,f);
            zos.finish();
            zos.close();
            fos.close();
            
            }catch(FileNotFoundException ex)
            {
               
            }catch(IOException ex)
            {
                
            }catch(JDOMException ex)
            {
                
            }
            
            
            JOptionPane.showMessageDialog(null, "Carta generada exitosamente");
            
            try {
                Runtime.getRuntime().exec("cmd /c start cartas/generada.docx");
            } catch (IOException ex) {
 
            }
            
            nom1.setText("");
            ced1.setText("");
            nac1.setText("");
            nom2.setText("");
            ced2.setText("");
            nac2.setText("");
            
            
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Algunos campos estan vacios");
        }
    }
    
    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        evento();
    }//GEN-LAST:event_crearActionPerformed

    private void ElemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ElemKeyPressed
        if(evt.getKeyCode()==10)
        {
            evento();
        }
    }//GEN-LAST:event_ElemKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ced1;
    private javax.swing.JTextField ced2;
    private javax.swing.JButton crear;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nac1;
    private javax.swing.JTextField nac2;
    private javax.swing.JTextField nom1;
    private javax.swing.JTextField nom2;
    // End of variables declaration//GEN-END:variables
}
