/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Habitante;
import java.util.HashMap;



/**
 *
 * @author Jessica
 */
public class Datos extends javax.swing.JPanel implements Componentes{

    /**
     * Creates new form Datos
     */
    Habitante h;
    Interna padre;
    
    public Datos(Interna in)
    {
        
        initComponents();
        
        padre=in;

        this.setBackground(ColorPrincipal);
         
        this.setBounds(80,370,850,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public String getMes(int m)
    {
        String ret="t";
        switch(m)
        {
            case  0: ret="Enero"; break;
            case  1: ret="Febrero"; break;
            case  2: ret="Marzo"; break;
            case  3: ret="Abril"; break;
            case  4: ret="Mayo"; break;
            case  5: ret="Junio"; break;
            case  6: ret="Julio"; break; 
            case  7: ret="Agosto"; break;
            case  8: ret="Septiembre"; break;
            case  9: ret="Octubre"; break;
            case 10: ret="Noviembre"; break;
            case 11: ret="Diciembre"; break;   
          
        }
        return ret;
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
