/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Jessica
 */
public class Estadisticas extends Interna {

    /**
     * Creates new form Cargar
     */
    String veredas[] = {"17        ","19        ","23        ","25        ","Z          ","21        ","Calle 5 ","8          ","4          ","6          "};
    
    public Estadisticas(JFrame previo) {
        
        super(previo,true);
        
        initComponents();

        this.setName("estadisticas");
        
        this.getContentPane().setBackground(ColorPrincipal);
        this.setBounds(dimForms);
        
        
        jButton1.setFont(Boton);
        jButton2.setFont(Boton);
        
        jLabel1.setFont(Etiqueta);
        jLabel1.setForeground(NegroEtiqueta);
        
        cbox.setVisible(false);
        cbox.addItem("Todas");
        for (int i = 0; i < veredas.length; i++)
        {
            cbox.addItem(veredas[i].trim());
        }
        
        jLabel1.setVisible(false);
        
        
        jTextArea1.setEditable(false);
        jPanel1.setVisible(false);
        jPanel1.setBackground(ColorPrincipal);
        
        this.repaint();
        
        this.setTitle("SistemaComunal - Estadisticas");
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cbox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Listado de familias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cantidad de familias por vereda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        cbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Vereda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(885, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getStr(int tam)
    {
        String str="";
        for (int i = 0; i < tam; i++)
        {
            str=" "+str;
        }
        return str;
    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jLabel1.setVisible(false);
        cbox.setVisible(false);
        jTextArea1.setText("");
        jPanel1.setVisible(true);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 24));
        for (int i = 0; i < veredas.length; i++)
        {
            String text=jTextArea1.getText();
            String data[][] = (String[][])op.select("Familia","direccion","direccion LIKE '%Vereda "+veredas[i].trim()+"%'",con);
            jTextArea1.setText(text+"\n        Vereda "+veredas[i]+"                        Numero de familias: "+data.length);
            
        }
        
        jTextArea1.setCaretPosition(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    public void mostrar_familias(String vereda)
    {
        String xver = "";
        if(vereda.compareTo("Todas")!=0)
        {
            xver = " and direccion LIKE '%Vereda "+vereda+"%'";
        }
        
        jTextArea1.setText("______________________________________________________________________________________");
        jPanel1.setVisible(true);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 14));
        String data[][] = (String[][])op.select_orderby("Familia, Persona","direccion, id_jefe, nombres, apellidos, cedula","Familia.id_jefe=Persona.id"+xver,"direccion", con);
        for (int i = 0; i < data.length; i++) 
        {
            String text=jTextArea1.getText();
            jTextArea1.setText(text+"\nDIRECCION: "+data[i][0]+"  JEFE FAMILIAR: "+data[i][2]+" "+data[i][3]+" C.I: "+data[i][4]);
            String id_famila=op.select("Familia","id","id_jefe="+data[i][1], con)[0][0].toString();
            
            String datam[][] = (String[][])op.select("Persona","nombres, apellidos, cedula","id_familia="+id_famila+" and id<>"+data[i][1], con);
            if(datam.length>0)
            {
                text=jTextArea1.getText();
                jTextArea1.setText(text+"\n\n              MIEMBROS:\n");
                
                for (int j = 0; j < datam.length; j++) 
                {
                    text=jTextArea1.getText();
                    jTextArea1.setText(text+"\n"+datam[j][0]+" "+datam[j][1]+" C.I: "+datam[j][2]);
                }    
            }
            text=jTextArea1.getText();
            jTextArea1.setText(text+"\n______________________________________________________________________________________");    
        }
        
        if(data.length==0)
        {
            jTextArea1.setText("");
            jPanel1.setVisible(false);
            JOptionPane.showMessageDialog(null, "No se encontraron familias registradas");
        }
        
        jTextArea1.setCaretPosition(0);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        jLabel1.setVisible(true);
        cbox.setVisible(true);
        cbox.setSelectedIndex(0);
        mostrar_familias(cbox.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxActionPerformed
        
        if(cbox.isVisible())
        mostrar_familias(cbox.getSelectedItem().toString());
    }//GEN-LAST:event_cboxActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
