/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JFrame;
/**
 *
 * @author Jessica
 */
public class Familia extends Interna {

    /**
     * Creates new form Familia1
     */
    public String id_familia;
    public Persona[] miembros  = new Persona[12];
    
    public Familia(JFrame previo)
    {
        super(previo,false);
        
        initComponents();
        
        this.setName("familia");
        
        this.getContentPane().setBackground(ColorPrincipal);
        this.setBounds(dimForms);
        
        nombre.setFont(Etiqueta);
        nombre.setForeground(NegroEtiqueta);
        apellido.setFont(Etiqueta);
        apellido.setForeground(NegroEtiqueta);
        cedula.setFont(Etiqueta);
        cedula.setForeground(NegroEtiqueta);
        direccion.setFont(Etiqueta);
        direccion.setForeground(NegroEtiqueta);
        
        jLabel1.setFont(Titulo);
        jLabel1.setForeground(NegroEtiqueta);
        
        jLabel2.setFont(Etiqueta);
        jLabel2.setForeground(BlancoEtiqueta);
        
        jLabel7.setFont(Etiqueta);
        jLabel7.setForeground(BlancoEtiqueta);
        jLabel7.setVisible(false);
        
        salir.setFont(Boton);
        
        for (int i = 0; i < 3; i++) 
        {
           miembros[4*i] = new Persona();
           miembros[4*i].setBounds(70,320+i*100,210,90);
           this.add(miembros[4*i]);
           miembros[4*i+1] = new Persona();
           miembros[4*i+1].setBounds(290,320+i*100,210,90);
           this.add(miembros[4*i+1]);
           miembros[4*i+2] = new Persona();
           miembros[4*i+2].setBounds(510,320+i*100,210,90);
           this.add(miembros[4*i+2]);
           miembros[4*i+3] = new Persona();
           miembros[4*i+3].setBounds(730,320+i*100,210,90);
           this.add(miembros[4*i+3]);
        }
        
        this.setTitle("SistemaComunal - Verificacion de Datos");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        apellido = new javax.swing.JLabel();
        cedula = new javax.swing.JLabel();
        direccion = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Datos de la familia");

        jLabel2.setText("Jefe familiar:");

        nombre.setText("jLabel3");

        apellido.setText("jLabel4");

        cedula.setText("jLabel5");

        direccion.setText("jLabel6");

        jLabel7.setText("Miembros");

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(464, 464, 464)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(266, 266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellido)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(salir)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.setVisible(false);
        Session.log.vista.setVisible(true);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
  

    public void set_id_familia(String id)
    {
        id_familia=id;
    }
    
    public void mostrar_jefe()
    {
        String dirr = op.select("Familia","direccion","id="+id_familia,con)[0][0].toString();
        
        String id_jefe = op.select("Familia","id_jefe","id="+id_familia,con)[0][0].toString();
        
        String datos[] = (String[])op.select("Persona","nombres, apellidos, cedula", "id="+id_jefe, con)[0];
        
        direccion.setText("Dirección: "+dirr);
        
        nombre.setText(datos[0]);
        
        apellido.setText(datos[1]);
        
        cedula.setText("C.I: "+datos[2]);
    }
    
    public void mostrar_miembros()
    {
        String id_jefe = op.select("Familia","id_jefe","id="+id_familia,con)[0][0].toString();
        
        String datos[][] = (String[][])op.select("Persona","nombres, apellidos, cedula","id_familia="+id_familia+" and id<>"+id_jefe, con);
        
        if(datos.length>0)
        {
            jLabel7.setVisible(true);
            for (int i = 0; i < datos.length; i++)
            {
                miembros[i].setNombre(datos[i][0]);
                miembros[i].setApellido(datos[i][1]);
                miembros[i].setCedula(datos[i][2]);
                miembros[i].setVisible(true);
            }           
        }
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel cedula;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel nombre;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
